# arxivの学問領域の指定
subject: 'cat:cs.*'
# 検索キーワード
keywords:
        anomaly detection: 1
        domain shift: 1
        transfer learning: 1
        semi-supervised learning: 1
        transformer: 3

# 通知の閾値
score_threshold: 0
